mdapi/objects/Camping_Item__c.object
<CustomObject>
    <label>Camping Item</label>
    <nameField>
        <label>Camping Item名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Packed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapi/objects/Expense__c.object
<CustomObject>
    <label>経費</label>
    <nameField>
        <label>経費名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/classes/CampingListController.cls
public with sharing class CampingListController {
    @AuraEnabled
    public static List<Camping_Item__c> getItems() {
/*
        List<String> fieldsToCheck = new List<string> {
            'Id', 'Name', 'Price__c', 'Quantity__c', 'Packed__c'
        };

        Map<String, Schema.SObjectField> fieldDescribeTokens = schema.SObjectType.Expense__c.fields.getMap();

        for (String field : fieldsToCheck) {
            if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
                return null;
            }
        }
*/
        return [
            SELECT
                Id,
                Name,
                Price__c,
                Quantity__c,
                Packed__c
            FROM
                Camping_Item__c
        ];
    }

    @AuraEnabled
    public static Camping_Item__c saveItem(Camping_Item__c item) {
        upsert item;
        return item;
    }
}