mdapi/objects/Expense__c.object
<CustomObject>
    <label>経費</label>
    <nameField>
        <label>経費名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <label>金額</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reimbursed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reimbursed</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/class/ExpensesController.cls
public with sharing class ExpensesController {
    // with sharing は組織の共有ルールが適応される。
    // オブジェクトレベルセキュリティ、項目レベルセキュリティなどは適応されない。
    @AuraEnabled
    public static List<Expense__c> getExpenses() {
        // check to make sure all fields are accessible to this user
        // describe コールはコストが高くなります。アプリケーションでこのメソッドを頻繁に
        // コールする場合、最適化する方法やユーザごとのアクセスチェックをキャッシュする方法を見つける必要があります。
        List<String> fieldsToCheck = new List<String> {
            'Id', 'Name', 'Amount__c', 'Client__c', 'Date__c', 'Reimbursed__c', 'CreateDate'
        };

        Map<String, Schema.SObjectField> fieldDescribeTokens = schema.SObjectType.Expense__c.fields.getMap();

        for (String field : fieldsToCheck) {
            if(!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
                return null;
            }
        }

        return [
            SELECT
                Id,
                Name,
                Amount__c,
                Client__c,
                Date__c,
                Reimbursed__c,
                CreatedDate
            FROM
                Expense__c
        ];
    }

    @AuraEnabled
    public static Expense__c saveExpense(Expense__c expense) {
        // 仮引数名はjavascriptのsetParamsで設定するパラメータ名と一致する必要がある
        upsert expense;
        return expense;
    }
}